### ISSUE TITLE
UCI version : severe error

### ISSUE THREAD

**Issue by tissatussa** [kurt1288/KhepriChess#10]
since v2.1.0 i can not execute the UCI version (i use the asset js file, not a compiled one).
i give this command in Linux terminal :

`$ node ./kheprichess_uci-3.0.0.js`

then i see output which is the complete js source (!?) and at the end these error messages are added :

```
SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

The same happens with your v2.1.0, but not with v1.1.0 .. what's wrong ?

**Comment by kurt1288** [comment]
What version of node do you have ("node -v")? If it's a version older than
16.x, are you able to update?

**Comment by tissatussa** [comment]
$ node -v
v12.22.9

> are you able to update?

i'm on Xubuntu 22.04 .. i will see how that's possible .. i will let you know.

**Comment by tissatussa** [comment]
at first i struggled to install a newer version, but i found https://github.com/nodesource/distributions/blob/master/README.md and i managed to install 18.x on my Xubuntu 22.04 .. now KhepriChess v3.0.0 is running fine !

$ node -v
v18.12.0

**Comment by kurt1288** [comment]
Glad to hear that fixed it!
